language: ruby
sudo: false

cache: bundler

bundler_args: --no-deployment --binstubs=./bin

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
  - gem update bundler

install:
  - bundle install --path vendor/bundle

script:
   - echo $BUNDLE_GEMFILE
   - bundle exec rake

gemfile:
  - gemfiles/capistrano_2.15.5.gemfile
  - gemfiles/capistrano_3.4.0.gemfile
rvm:
  - 2.2.5
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.4.0
notifications:
  email: false
